name: shoppingapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  flutter_slidable: ^2.0.0
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  bloc: ^8.0.3
  dio: ^4.0.6
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  flutter_conditional_rendering: ^2.0.0
  shared_preferences: ^2.0.15
  shrink_sidemenu: ^2.0.0+2-null-safety


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/on1.png
    - images/on2.png
    - images/on3.png
    
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-ExtraLight.ttf
        - asset: fonts/NotoSans-Light.ttf
        - asset: fonts/NotoSans-Regular.ttf
          style: italic